# Generated by Django 4.0.3 on 2022-03-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
